### ISSUE TITLE
how to use it in for jquery

### ISSUE THREAD

**Issue by nosun** [kfirba/Mavigator#2]
I saw your post at laracast, I don`t know how to use the script in laravel project.

**Comment by kfirba** [comment]
@nosun hey.

it's really simple. All you have to do is to run:

```
npm install mavigator --save
```

Now you just need to import and invoke the script. 

Assuming you are using Laravel Elixir and your entry point is `resources/assets/js/main.js` you should add in that file these lines:

```
import Mavigator from 'mavigator';

Mavigator.mark();
```

Now just make sure you reference the compiled file in your layout file just above the closing tag of the `<body>`.

**Comment by nosun** [comment]
Thank you very much, I have a try right now

**Comment by nosun** [comment]
I make a common.js  at the resource dir, and use elixir compile it to the public dir:

common.js

```
import Mavigator from 'mavigator';
Mavigator.mark();
```

part of gulp.js 

```
mix.browserify(['common.js'],  'public/js/common.js');
```

when I run the script at broswer, I met the error like this:

the error information

```
TypeError: sets.forEach is not a function
```

Is there something wrong?

**Comment by kfirba** [comment]
@nosun what browser are you using?

**Comment by nosun** [comment]
firefox 48.0

**Comment by nosun** [comment]
chrome not declare error, but not working~

**Comment by kfirba** [comment]
@nosun can you run the script with the `warn` flag on and run it on chrome again?

```
Mavigator.mark('body', {warn: true});
```

**Comment by nosun** [comment]
If I put the js before the `<body>` tag, the console show:

```
No link to mark was found for the given URI [/script/uploadComments]
```

If I put the js at the end of the html but before `</body>` , It show error still

```
TypeError: sets.forEach is not a function

```

**Comment by kfirba** [comment]
@nosun you shouldn't put the script before the `<body>` element as the DOM hasn't loaded yet. If you want to put it before the `<body>` you should wrap the code in an event listener that listens when the DOM is ready.

I think I know where the issue is. It's due to your browser not falling back to the `Array.prototype` methods on the `NodeList` returned internally. 

I'm currently not home so I can't push a quick fix but I will do so as soon as possible. I will let you know when I push an update that fixes this.

Thanks for reporting it and testing!

**Comment by nosun** [comment]
haha~, you are welcome! I will testing it later

**Comment by kfirba** [comment]
@nosun Hey!

I've just pushed an update attempting to fix this (https://github.com/kfirba/Mavigator/commit/001bb71fcc0467b1fa68ab4025bbde8bbf8a5cdf).

Make sure to pull the new version from NPM (v1.0.2)

Let me know if it works for you!

**Comment by kfirba** [comment]
@nosun hey. I've never heard back from you. Does it work for you now?

**Comment by nosun** [comment]
@kfirba , I am very sorry, these two days I am very busy at the other things, I will test it at tomorrow.

**Comment by nosun** [comment]
@kfirba , I test it again, now there is no error report, but still not working for me

**Comment by kfirba** [comment]
@nosun Hey.

That's really weird. Can you please help me reproduce that issue on my side? Please share your HTML, CSS and JS with me so I can also test it. I tried reproducing it for a while now but just couldn't

**Comment by nosun** [comment]
@kfirba , ok, I will build a project for your test, give me sometime.

**Comment by nosun** [comment]
@kfirba  pls see the repo https://github.com/nosun/laravel_blog, use the branch blog. I use adminlte as admin template.

```
composer install
config setting
and then gulp
```

I write some menu at the side bar,you can test it.

**Comment by kfirba** [comment]
@nosun Hey.

I've inspected your repository and the code in it and also tested it.

Everything works just fine. I can see the `active` class being added to every element that matches the criteria.

Just to ensure you see that it's working, add this CSS rule to one of you `less` files:

``` css
*.active {
    background-color: black !important;
}
```

Now you should see every link that matches the marking criteria, with a black background.

The only thing I will need to think about is links that have `hashtags(#)` in their `href` attribute. What's happening that if a link looks like:

``` html
<a href="#">My Text</a>
```

The real `href` that's being assigned to it is (and as it's being compiled by the browser) - assuming that we are on `example.com/index`

``` html
<a href="/index#">My Text</a>
```

So Mavgiator does mark it. I may need to add an option to disable/enable it but you can work around it by narrowing down your selector:

``` js
Mavigator.mark('.my-side-nav');
```

Let me know if you have any question!

**Comment by nosun** [comment]
Its my fault~ the code is ok! You really high efficiency

btw: I think If the child be matched, there parent also need be active.

**Comment by kfirba** [comment]
@nosun cool.

You can add a property that will mark the parent instead of the link itself:

``` js
Mavigator.mark('body', {classToParent: true});
```

Now if your HTML looks like:

``` html
<li>
    <a href="/">Home</a>
</li>
```

It will look like:

``` html
<li class="active">
    <a href="/">Home</a>
</li>
```

In your CSS you can match both:

``` css
li.active, li.active > a {
    color: blue;
}
```
